// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2OyrsDVHC7Ufj7ObbhOeV7wmRmuDvQY',
    appId: '1:532044324935:web:ab82724d6e452c9fa91162',
    messagingSenderId: '532044324935',
    projectId: 'uccd-tanta-university',
    authDomain: 'uccd-tanta-university.firebaseapp.com',
    storageBucket: 'uccd-tanta-university.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvu18ImdnodVDRuyGwtmQKuq35rMj0Ag0',
    appId: '1:532044324935:android:9955dfe89c97e48ca91162',
    messagingSenderId: '532044324935',
    projectId: 'uccd-tanta-university',
    storageBucket: 'uccd-tanta-university.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqqlbA8sacF4h1KcFarVoMDGGw9mRm1I',
    appId: '1:532044324935:ios:77a6c0bd09a44a4ea91162',
    messagingSenderId: '532044324935',
    projectId: 'uccd-tanta-university',
    storageBucket: 'uccd-tanta-university.appspot.com',
    iosClientId: '532044324935-g6vvs57npdnffpt8r0ohdpbum809thgp.apps.googleusercontent.com',
    iosBundleId: 'com.sabahya10.se',
  );
}
